app <- ShinyDriver$new("../../")
app$snapshotInit("test_app_htn")

app$setInputs(`RunCodelistBuilder-disease` = "Hypertension")
app$setInputs(`RunCodelistBuilder-author` = "Me")
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "read2", "read3", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "read3", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "data_coding_5", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = c("icd10", "data_coding_6"))
app$setInputs(`RunCodelistBuilder-code_type` = "icd10")
app$setInputs(`RunCodelistBuilder-description_search` = "hypertension")
app$setInputs(`RunCodelistBuilder-description_search_and` = "e")
app$setInputs(`RunCodelistBuilder-description_search_and` = "essential")
app$setInputs(`RunCodelistBuilder-description_search_and` = "essential|primary")
app$setInputs(`RunCodelistBuilder-description_search_not` = "intracranial")
app$setInputs(`RunCodelistBuilder-description_search_not` = "intracranial|")
app$setInputs(`RunCodelistBuilder-description_search_not` = "intracranial|pulmonary")
app$setInputs(`RunCodelistBuilder-new_search` = "click")
app$setInputs(tabs = "Matching clinical codes")
app$setInputs(tabs = "Preview selected codes only")
app$snapshotDownload("RunCodelistBuilder-download_confirmed_codes")
