app <- ShinyDriver$new("../../")
app$snapshotInit("test-app")

app$setInputs(disease = "Hypertension")
app$setInputs(code_type = c("icd10", "read2", "read3", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "read3", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "opcs4", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "data_coding_3", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "data_coding_4", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "data_coding_5", "data_coding_6"))
app$setInputs(code_type = c("icd10", "data_coding_6"))
app$setInputs(code_type = "icd10")
app$setInputs(description_search = "Hy")
app$setInputs(description_search = "")
app$setInputs(description_search = "hy")
app$setInputs(description_search = "hypertension")
app$setInputs(description_search_and = "essential")
app$setInputs(description_search_and = "essential|primary")
app$setInputs(description_search_not = "pulmonary")
app$setInputs(description_search_not = "pulmonary|")
app$setInputs(description_search_not = "pulmonary|intracr")
app$setInputs(description_search_not = "pulmonary|intracranial")
app$setInputs(new_search = "click")
app$snapshot()
